# Generated by Django 2.2.9 on 2019-12-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0006_auto_20191219_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='many_to_many.Topping', verbose_name='토핑 추가'),
        ),
    ]
