# Generated by Django 2.2.9 on 2019-12-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0008_auto_20191222_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='customers',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
